@extends('layouts.admin')
@section('title', 'Danh mục Combo')
@section('page-title', 'Danh mục Combo')
@section('breadcrumbs')<ol class="breadcrumb float-sm-end mb-0"><li class="breadcrumb-item"><a href="{{ route('admin.dashboard') }}">Dashboard</a></li><li class="breadcrumb-item active">Danh mục Combo</li></ol>@endsection
@section('content')
<x-admin.index-card title="Danh mục Combo" description="Phân nhóm Combo độc lập với danh mục sản phẩm." icon="bi-diagram-3" :create-url="route('admin.combo-categories.create')" create-label="Thêm danh mục" resource="combo_category" :bulk-actions="['activate' => 'Hiển thị', 'deactivate' => 'Ẩn']" :reorderable="true" :reorder-enabled="! request()->hasAny(['search', 'status', 'per_page'])" :order-start="$categories->firstItem() ?? 1">
    <x-slot:filters><form action="{{ route('admin.combo-categories.index') }}" method="GET" class="row g-2 align-items-end"><div class="col-md-7"><label class="form-label">Từ khóa</label><input class="form-control" name="search" value="{{ request('search') }}" placeholder="Tên hoặc slug"></div><div class="col-md-3"><label class="form-label">Trạng thái</label><select class="form-select" name="status"><option value="">Tất cả</option><option value="active" @selected(request('status') === 'active')>Đang hiển thị</option><option value="inactive" @selected(request('status') === 'inactive')>Đang ẩn</option></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="bi bi-funnel me-1"></i>Lọc</button></div></form></x-slot:filters>
    <div class="table-responsive"><table class="table table-hover align-middle"><thead><tr><th data-select-column class="text-center" style="width:48px"><input type="checkbox" class="form-check-input" data-check-all aria-label="Chọn tất cả"></th><th>Tên</th><th>Đường dẫn</th><th class="text-center">Combo</th><th class="text-center">Trạng thái</th><th class="text-end">Thao tác</th></tr></thead><tbody>@forelse($categories as $category)<tr data-record-id="{{ $category->id }}"><td data-select-column class="text-center"><input form="admin-bulk-combo_category-form" type="checkbox" name="ids[]" value="{{ $category->id }}" class="form-check-input" data-check-item aria-label="Chọn {{ $category->name }}"></td><td><strong>{{ $category->name }}</strong></td><td class="text-muted">/{{ $category->slug }}</td><td class="text-center">{{ number_format($category->combos_count) }}</td><td class="text-center"><x-toggle model="ComboCategory" :id="$category->id" field="is_active" :checked="$category->is_active" label="" /></td><td class="text-end"><div class="btn-group btn-group-sm"><a class="btn btn-default" href="{{ route('admin.combo-categories.edit', $category) }}"><i class="bi bi-pencil"></i></a><button type="submit" form="delete-combo-category-{{ $category->id }}" class="btn btn-default text-danger"><i class="bi bi-trash"></i></button></div></td></tr><form id="delete-combo-category-{{ $category->id }}" action="{{ route('admin.combo-categories.destroy', $category) }}" method="POST" class="d-none" data-admin-delete-form data-delete-title="Xóa danh mục này?" data-delete-warning="Danh mục đang có Combo sẽ không thể xóa.">@csrf @method('DELETE')</form>@empty<tr><td colspan="6" class="text-center py-5">Chưa có danh mục Combo.</td></tr>@endforelse</tbody></table></div>
    <x-slot:footer>@if($categories->hasPages()){{ $categories->links() }}@endif</x-slot:footer>
</x-admin.index-card>
@endsection
