<?php

return [
    'permissions' => [
        'view dashboard' => ['group' => 'Tổng quan', 'label' => 'Xem bảng điều khiển'],
        'view orders' => ['group' => 'Bán hàng', 'label' => 'Xem đơn hàng'],
        'update order status' => ['group' => 'Bán hàng', 'label' => 'Cập nhật trạng thái đơn hàng'],
        'view payments' => ['group' => 'Thanh toán', 'label' => 'Xem phiếu thanh toán và giao dịch ngân hàng'],
        'create manual payments' => ['group' => 'Thanh toán', 'label' => 'Tạo và sửa phiếu thanh toán thủ công'],
        'reconcile payments' => ['group' => 'Thanh toán', 'label' => 'Chạy đối soát SePay'],
        'override payment status' => ['group' => 'Thanh toán', 'label' => 'Gắn giao dịch và xử lý ngoại lệ thanh toán'],
        'manage payment settings' => ['group' => 'Thanh toán', 'label' => 'Quản lý cấu hình thanh toán SePay'],
        'view webhook logs' => ['group' => 'Thanh toán', 'label' => 'Xem payload webhook và dữ liệu audit'],
        'manage products' => ['group' => 'Sản phẩm', 'label' => 'Quản lý sản phẩm, danh mục, thương hiệu và thuộc tính'],
        'manage promotions' => ['group' => 'Bán hàng', 'label' => 'Quản lý Flash Sale và mã giảm giá'],
        'manage content' => ['group' => 'Nội dung', 'label' => 'Quản lý trang, bài viết, slider và menu'],
        'manage customers' => ['group' => 'CRM', 'label' => 'Quản lý khách hàng'],
        'manage contacts' => ['group' => 'CRM', 'label' => 'Quản lý liên hệ, đăng ký, đánh giá và bình luận'],
        'manage settings' => ['group' => 'Hệ thống', 'label' => 'Quản lý cài đặt website'],
        'manage users' => ['group' => 'Hệ thống', 'label' => 'Quản lý tài khoản quản trị'],
        'manage roles' => ['group' => 'Hệ thống', 'label' => 'Quản lý vai trò và phân quyền'],
    ],

    // Prefix route được xét từ trên xuống; route không khai báo sẽ bị từ chối mặc định.
    'route_permissions' => [
        'admin.dashboard' => ['view dashboard'],
        'admin.orders.update' => ['update order status'],
        'admin.orders.destroy' => ['update order status'],
        'admin.orders.' => ['view orders'],
        'admin.payments.create' => ['create manual payments'],
        'admin.payments.store' => ['create manual payments'],
        'admin.payments.edit' => ['create manual payments'],
        'admin.payments.update' => ['create manual payments'],
        'admin.payments.destroy' => ['create manual payments'],
        'admin.payments.' => ['view payments'],
        'admin.payment-transactions.attach' => ['override payment status'],
        'admin.payment-transactions.show' => ['view webhook logs'],
        'admin.payment-transactions.' => ['view payments'],
        'admin.settings.payment.reconcile' => ['reconcile payments'],
        'admin.settings.payment.test-connection' => ['manage payment settings'],
        'admin.settings.payment' => ['manage payment settings'],
        'admin.products.' => ['manage products'],
        'admin.combos.' => ['manage products'],
        'admin.combo-categories.' => ['manage products'],
        'admin.product-categories.' => ['manage products'],
        'admin.product-options.' => ['manage products'],
        'admin.product-attributes.' => ['manage products'],
        'admin.brands.' => ['manage products'],
        'admin.flash-sales.' => ['manage promotions'],
        'admin.coupons.' => ['manage promotions'],
        'admin.pages.' => ['manage content'],
        'admin.post-categories.' => ['manage content'],
        'admin.posts.' => ['manage content'],
        'admin.slider-items.' => ['manage content'],
        'admin.sliders.' => ['manage content'],
        'admin.testimonials.' => ['manage content'],
        'admin.menus.' => ['manage content'],
        'admin.contacts.' => ['manage contacts'],
        'admin.subscribers.' => ['manage contacts'],
        'admin.reviews.' => ['manage contacts'],
        'admin.comments.' => ['manage contacts'],
        'admin.settings.' => ['manage settings'],
        'admin.users.' => ['manage users'],
        'admin.roles.' => ['manage roles'],
        'admin.profile' => [],
    ],

    'resource_permissions' => [
        'flash_sale' => 'manage promotions',
        'coupon' => 'manage promotions',
        'order' => 'update order status',
        'slider' => 'manage content',
        'post' => 'manage content',
        'post_category' => 'manage content',
        'page' => 'manage content',
        'testimonial' => 'manage content',
        'product' => 'manage products',
        'combo' => 'manage products',
        'combo_category' => 'manage products',
        'product_category' => 'manage products',
        'brand' => 'manage products',
        'product_option' => 'manage products',
        'product_attribute' => 'manage products',
        'contact' => 'manage contacts',
        'subscriber' => 'manage contacts',
        'custom_request' => 'manage custom requests',
    ],

    'model_permissions' => [
        'Slider' => 'manage content',
        'SliderItem' => 'manage content',
        'Testimonial' => 'manage content',
        'Menu' => 'manage content',
        'MenuItem' => 'manage content',
        'Page' => 'manage content',
        'Post' => 'manage content',
        'PostCategory' => 'manage content',
        'Product' => 'manage products',
        'Combo' => 'manage products',
        'ComboCategory' => 'manage products',
        'ProductCategory' => 'manage products',
        'Brand' => 'manage products',
        'ProductOption' => 'manage products',
        'ProductAttribute' => 'manage products',
        'Subscriber' => 'manage contacts',
    ],

    'media_permissions' => [
        'manage products',
        'manage content',
        'manage settings',
    ],
];
