@extends('layouts.master')
@section('title','Thanh toán — '.$website['name'])
@section('content')
<div class="breadcrumb-wrap"><div class="container"><nav><ol class="breadcrumb"><li class="breadcrumb-item"><a href="{{ route('cart') }}">Giỏ hàng</a></li><li class="breadcrumb-item active">Thanh toán</li></ol></nav></div></div>
<section class="section-space bg-soft"><div class="container"><x-section-heading title="Thông tin đặt hàng" :center="false" />
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<form action="{{ route('checkout.store') }}" method="post">@csrf<div class="row g-4 align-items-start"><div class="col-lg-8">
<div class="content-card mb-3"><h2 class="h5 fw-bold mb-3">Thông tin người nhận</h2><div class="row g-3"><div class="col-md-6"><label class="form-label">Họ và tên *</label><input class="form-control" name="customer_name" value="{{ old('customer_name',auth()->user()?->name) }}" required></div><div class="col-md-6"><label class="form-label">Số điện thoại *</label><input class="form-control" name="customer_phone" value="{{ old('customer_phone',auth()->user()?->phone) }}" required></div><div class="col-12"><label class="form-label">Email</label><input class="form-control" type="email" name="customer_email" value="{{ old('customer_email',auth()->user()?->email) }}"></div></div></div>
<div class="content-card mb-3"><h2 class="h5 fw-bold mb-3">Địa chỉ giao hàng</h2><div class="row g-3"><div class="col-md-4"><label class="form-label">Tỉnh/Thành phố *</label><input class="form-control" name="shipping_province" value="{{ old('shipping_province') }}" required></div><div class="col-md-4"><label class="form-label">Quận/Huyện</label><input class="form-control" name="shipping_district" value="{{ old('shipping_district') }}"></div><div class="col-md-4"><label class="form-label">Phường/Xã</label><input class="form-control" name="shipping_ward" value="{{ old('shipping_ward') }}"></div><div class="col-12"><label class="form-label">Địa chỉ cụ thể *</label><input class="form-control" name="shipping_address" value="{{ old('shipping_address') }}" required></div><div class="col-12"><label class="form-label">Ghi chú</label><textarea class="form-control" name="note" rows="3">{{ old('note') }}</textarea></div></div></div>
<div class="content-card"><h2 class="h5 fw-bold mb-3">Phương thức thanh toán</h2><div class="form-check border rounded-3 p-3 ps-5 mb-2"><input class="form-check-input" type="radio" name="payment_method" id="cod" value="cod" checked><label class="form-check-label fw-bold" for="cod">Thanh toán khi nhận hàng (COD)</label></div><div class="form-check border rounded-3 p-3 ps-5"><input class="form-check-input" type="radio" name="payment_method" id="bank" value="bank_transfer"><label class="form-check-label fw-bold" for="bank">Chuyển khoản ngân hàng</label></div></div>
</div><aside class="col-lg-4"><div class="cart-summary sticky-lg-top" style="top:1rem"><h2 class="h5 fw-bold mb-3">Đơn hàng của bạn</h2>@foreach($cart->items as $item)<div class="d-flex gap-2 py-2 border-bottom"><img class="cart-product-img" src="{{ $item->variant?->image ?: $item->product->image_url }}" alt="" width="80" height="80"><div class="small flex-grow-1"><strong>{{ $item->product->name }}</strong><div class="text-muted">SL: {{ $item->quantity }}</div></div><strong class="small">{{ number_format($item->unit_price*$item->quantity,0,',','.') }}₫</strong></div>@endforeach<div class="d-flex justify-content-between mt-3"><span>Tạm tính</span><strong>{{ number_format($summary['subtotal'],0,',','.') }}₫</strong></div><div class="d-flex justify-content-between mt-2"><span>Giảm giá</span><span>-{{ number_format($summary['discount'],0,',','.') }}₫</span></div><div class="d-flex justify-content-between mt-2"><span>Vận chuyển</span><span>{{ $summary['shipping']?number_format($summary['shipping'],0,',','.').'₫':'Miễn phí' }}</span></div><hr><div class="d-flex justify-content-between fs-5"><strong>Tổng cộng</strong><strong class="text-primary">{{ number_format($summary['total'],0,',','.') }}₫</strong></div><button class="btn btn-primary w-100 py-3 mt-3">Đặt hàng</button><p class="small text-muted text-center mt-2 mb-0">Bằng việc đặt hàng, anh/chị đồng ý với chính sách mua hàng.</p></div></aside></div></form></div></section>
@endsection

